title: UW Robot Learning
logo: ./assets/logo.png
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true

remote_theme: pmarsceill/just-the-docs
search_enabled: true 
compress_html:
  blanklines: true
mathjax:
  source: https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/latest.js?config=TeX-AMS_CHTML
  config: 'MathJax.Hub.Config({ TeX: { equationNumbers: { autoNumber: "AMS" } } })'
mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "10.5.0"
