title: UW Robot Learning
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true

remote_theme: pmarsceill/just-the-docs
search_enabled: true 
compress_html:
  blanklines: true
